// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type Sensor struct {
	ID           int64
	SensorName   sql.NullString
	SensorType   sql.NullString
	SensorDevice sql.NullString
	SensorSource sql.NullString
	UserLabel    sql.NullString
	UserUnits    sql.NullString
	ShouldLog    sql.NullInt64
	SensorOrder  sql.NullInt64
}

type SensorLog struct {
	SensorID      sql.NullInt64
	Timestamp     sql.NullString
	SensorReading sql.NullFloat64
}

type Setting struct {
	ID    int64
	Name  sql.NullString
	Value sql.NullString
}
